### ISSUE TITLE
ClassCircularityError on Tc 6 and 7 deployment

### ISSUE THREAD

**Issue by szuzul** [play2war/play2-war-plugin#80]
After creating WAR file, on startup Tomcat server, I get exception:

INFO: Deploying web application archive C:\Java\apache-tomcat-7.0.29\webapps\ROOT.war
27.08.2012. 10:14:26 org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
java.lang.ClassCircularityError: java/util/logging/LogRecord
at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:179)
at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:268)
at java.util.logging.Logger.log(Logger.java:458)
at java.util.logging.Logger.doLog(Logger.java:480)
at java.util.logging.Logger.logp(Logger.java:596)
at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:183)
at org.apache.juli.logging.DirectJDKLog.debug(DirectJDKLog.java:106)
at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:368)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
at org.apache.catalina.startup.Catalina.start(Catalina.java:675)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:322)
at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:451)

Play 2.0.2
SBT 0.11.3
Tomcat 7.0.29 (servlet 3 packing) or Tomcat 6.0.29 (servlet 2.5 packing) exception is same.
JRE: 1.6.0_22-b04

Packing process finished without errors:
[info] Resolving org.easytesting#fest-util;1.1.6 ...
[info] Done updating.
[info] Build WAR package for servlet container: 3.0
[info] Packaging C:\workspace\HelloWorldWeb\target\helloworldweb-1.0.war ...
[info] Packaging done.
[success] Total time: 15 s, completed 27.08.2012. 10:36:40
logger.xml is copy paste from https://github.com/dlecan/play2-war-plugin#configure-logging

Best regards,

**Comment by dlecan** [comment]
I will look at that.
Thanks

**Comment by szuzul** [comment]
Cool, thanks..

**Comment by dlecan** [comment]
Should be fixed by #54

**Comment by dlecan** [comment]
Play2War 0.8 has been released, with a fix for this issue.

**Comment by snowdream** [comment]
Not fixed: ClassCircularityError on Tomcat 7 deployment ,with play framework 2.1.1

Apache Tomcat/7.0.30

**Comment by dlecan** [comment]
@snowdream See [this comment](https://github.com/dlecan/play2-war-plugin/issues/138#issuecomment-14785516), it might help you.
